In [1]:
import torch

In [2]:
x = torch.empty(3, 5)

In [3]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [5]:
y = torch.rand(3, 4)

In [6]:
y

tensor([[0.1502, 0.3266, 0.9480, 0.1442],
        [0.2440, 0.8858, 0.1864, 0.4038],
        [0.2824, 0.8427, 0.2500, 0.7354]])

In [7]:
z = torch.ones(3, 4)

In [8]:
print(z)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [17]:
x.dtype

torch.float32